# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhangyilei/Downloads/Exiv2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhangyilei/Downloads/Exiv2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.12.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.12.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangyilei/Downloads/Exiv2/CMakeFiles /Users/zhangyilei/Downloads/Exiv2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangyilei/Downloads/Exiv2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named exiv2-xmp

# Build rule for target.
exiv2-xmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exiv2-xmp
.PHONY : exiv2-xmp

# fast build rule for target.
exiv2-xmp/fast:
	$(MAKE) -f xmpsdk/CMakeFiles/exiv2-xmp.dir/build.make xmpsdk/CMakeFiles/exiv2-xmp.dir/build
.PHONY : exiv2-xmp/fast

#=============================================================================
# Target rules for targets named exiv2

# Build rule for target.
exiv2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exiv2
.PHONY : exiv2

# fast build rule for target.
exiv2/fast:
	$(MAKE) -f src/CMakeFiles/exiv2.dir/build.make src/CMakeFiles/exiv2.dir/build
.PHONY : exiv2/fast

#=============================================================================
# Target rules for targets named exiv2lib

# Build rule for target.
exiv2lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exiv2lib
.PHONY : exiv2lib

# fast build rule for target.
exiv2lib/fast:
	$(MAKE) -f src/CMakeFiles/exiv2lib.dir/build.make src/CMakeFiles/exiv2lib.dir/build
.PHONY : exiv2lib/fast

#=============================================================================
# Target rules for targets named exiv2lib_int

# Build rule for target.
exiv2lib_int: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exiv2lib_int
.PHONY : exiv2lib_int

# fast build rule for target.
exiv2lib_int/fast:
	$(MAKE) -f src/CMakeFiles/exiv2lib_int.dir/build.make src/CMakeFiles/exiv2lib_int.dir/build
.PHONY : exiv2lib_int/fast

#=============================================================================
# Target rules for targets named remotetest

# Build rule for target.
remotetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remotetest
.PHONY : remotetest

# fast build rule for target.
remotetest/fast:
	$(MAKE) -f samples/CMakeFiles/remotetest.dir/build.make samples/CMakeFiles/remotetest.dir/build
.PHONY : remotetest/fast

#=============================================================================
# Target rules for targets named geotag

# Build rule for target.
geotag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geotag
.PHONY : geotag

# fast build rule for target.
geotag/fast:
	$(MAKE) -f samples/CMakeFiles/geotag.dir/build.make samples/CMakeFiles/geotag.dir/build
.PHONY : geotag/fast

#=============================================================================
# Target rules for targets named exiv2json

# Build rule for target.
exiv2json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exiv2json
.PHONY : exiv2json

# fast build rule for target.
exiv2json/fast:
	$(MAKE) -f samples/CMakeFiles/exiv2json.dir/build.make samples/CMakeFiles/exiv2json.dir/build
.PHONY : exiv2json/fast

#=============================================================================
# Target rules for targets named pathtest

# Build rule for target.
pathtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pathtest
.PHONY : pathtest

# fast build rule for target.
pathtest/fast:
	$(MAKE) -f samples/CMakeFiles/pathtest.dir/build.make samples/CMakeFiles/pathtest.dir/build
.PHONY : pathtest/fast

#=============================================================================
# Target rules for targets named metacopy

# Build rule for target.
metacopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metacopy
.PHONY : metacopy

# fast build rule for target.
metacopy/fast:
	$(MAKE) -f samples/CMakeFiles/metacopy.dir/build.make samples/CMakeFiles/metacopy.dir/build
.PHONY : metacopy/fast

#=============================================================================
# Target rules for targets named getopt-test

# Build rule for target.
getopt-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 getopt-test
.PHONY : getopt-test

# fast build rule for target.
getopt-test/fast:
	$(MAKE) -f samples/CMakeFiles/getopt-test.dir/build.make samples/CMakeFiles/getopt-test.dir/build
.PHONY : getopt-test/fast

#=============================================================================
# Target rules for targets named xmpdump

# Build rule for target.
xmpdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmpdump
.PHONY : xmpdump

# fast build rule for target.
xmpdump/fast:
	$(MAKE) -f samples/CMakeFiles/xmpdump.dir/build.make samples/CMakeFiles/xmpdump.dir/build
.PHONY : xmpdump/fast

#=============================================================================
# Target rules for targets named xmpprint

# Build rule for target.
xmpprint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmpprint
.PHONY : xmpprint

# fast build rule for target.
xmpprint/fast:
	$(MAKE) -f samples/CMakeFiles/xmpprint.dir/build.make samples/CMakeFiles/xmpprint.dir/build
.PHONY : xmpprint/fast

#=============================================================================
# Target rules for targets named xmpparse

# Build rule for target.
xmpparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmpparse
.PHONY : xmpparse

# fast build rule for target.
xmpparse/fast:
	$(MAKE) -f samples/CMakeFiles/xmpparse.dir/build.make samples/CMakeFiles/xmpparse.dir/build
.PHONY : xmpparse/fast

#=============================================================================
# Target rules for targets named stringto-test

# Build rule for target.
stringto-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringto-test
.PHONY : stringto-test

# fast build rule for target.
stringto-test/fast:
	$(MAKE) -f samples/CMakeFiles/stringto-test.dir/build.make samples/CMakeFiles/stringto-test.dir/build
.PHONY : stringto-test/fast

#=============================================================================
# Target rules for targets named write-test

# Build rule for target.
write-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write-test
.PHONY : write-test

# fast build rule for target.
write-test/fast:
	$(MAKE) -f samples/CMakeFiles/write-test.dir/build.make samples/CMakeFiles/write-test.dir/build
.PHONY : write-test/fast

#=============================================================================
# Target rules for targets named iptctest

# Build rule for target.
iptctest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iptctest
.PHONY : iptctest

# fast build rule for target.
iptctest/fast:
	$(MAKE) -f samples/CMakeFiles/iptctest.dir/build.make samples/CMakeFiles/iptctest.dir/build
.PHONY : iptctest/fast

#=============================================================================
# Target rules for targets named tiff-test

# Build rule for target.
tiff-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff-test
.PHONY : tiff-test

# fast build rule for target.
tiff-test/fast:
	$(MAKE) -f samples/CMakeFiles/tiff-test.dir/build.make samples/CMakeFiles/tiff-test.dir/build
.PHONY : tiff-test/fast

#=============================================================================
# Target rules for targets named conntest

# Build rule for target.
conntest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conntest
.PHONY : conntest

# fast build rule for target.
conntest/fast:
	$(MAKE) -f samples/CMakeFiles/conntest.dir/build.make samples/CMakeFiles/conntest.dir/build
.PHONY : conntest/fast

#=============================================================================
# Target rules for targets named largeiptc-test

# Build rule for target.
largeiptc-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 largeiptc-test
.PHONY : largeiptc-test

# fast build rule for target.
largeiptc-test/fast:
	$(MAKE) -f samples/CMakeFiles/largeiptc-test.dir/build.make samples/CMakeFiles/largeiptc-test.dir/build
.PHONY : largeiptc-test/fast

#=============================================================================
# Target rules for targets named ini-test

# Build rule for target.
ini-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ini-test
.PHONY : ini-test

# fast build rule for target.
ini-test/fast:
	$(MAKE) -f samples/CMakeFiles/ini-test.dir/build.make samples/CMakeFiles/ini-test.dir/build
.PHONY : ini-test/fast

#=============================================================================
# Target rules for targets named taglist

# Build rule for target.
taglist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taglist
.PHONY : taglist

# fast build rule for target.
taglist/fast:
	$(MAKE) -f samples/CMakeFiles/taglist.dir/build.make samples/CMakeFiles/taglist.dir/build
.PHONY : taglist/fast

#=============================================================================
# Target rules for targets named xmpparser-test

# Build rule for target.
xmpparser-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmpparser-test
.PHONY : xmpparser-test

# fast build rule for target.
xmpparser-test/fast:
	$(MAKE) -f samples/CMakeFiles/xmpparser-test.dir/build.make samples/CMakeFiles/xmpparser-test.dir/build
.PHONY : xmpparser-test/fast

#=============================================================================
# Target rules for targets named mmap-test

# Build rule for target.
mmap-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mmap-test
.PHONY : mmap-test

# fast build rule for target.
mmap-test/fast:
	$(MAKE) -f samples/CMakeFiles/mmap-test.dir/build.make samples/CMakeFiles/mmap-test.dir/build
.PHONY : mmap-test/fast

#=============================================================================
# Target rules for targets named key-test

# Build rule for target.
key-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 key-test
.PHONY : key-test

# fast build rule for target.
key-test/fast:
	$(MAKE) -f samples/CMakeFiles/key-test.dir/build.make samples/CMakeFiles/key-test.dir/build
.PHONY : key-test/fast

#=============================================================================
# Target rules for targets named werror-test

# Build rule for target.
werror-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 werror-test
.PHONY : werror-test

# fast build rule for target.
werror-test/fast:
	$(MAKE) -f samples/CMakeFiles/werror-test.dir/build.make samples/CMakeFiles/werror-test.dir/build
.PHONY : werror-test/fast

#=============================================================================
# Target rules for targets named iptceasy

# Build rule for target.
iptceasy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iptceasy
.PHONY : iptceasy

# fast build rule for target.
iptceasy/fast:
	$(MAKE) -f samples/CMakeFiles/iptceasy.dir/build.make samples/CMakeFiles/iptceasy.dir/build
.PHONY : iptceasy/fast

#=============================================================================
# Target rules for targets named iptcprint

# Build rule for target.
iptcprint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iptcprint
.PHONY : iptcprint

# fast build rule for target.
iptcprint/fast:
	$(MAKE) -f samples/CMakeFiles/iptcprint.dir/build.make samples/CMakeFiles/iptcprint.dir/build
.PHONY : iptcprint/fast

#=============================================================================
# Target rules for targets named exifprint

# Build rule for target.
exifprint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exifprint
.PHONY : exifprint

# fast build rule for target.
exifprint/fast:
	$(MAKE) -f samples/CMakeFiles/exifprint.dir/build.make samples/CMakeFiles/exifprint.dir/build
.PHONY : exifprint/fast

#=============================================================================
# Target rules for targets named convert-test

# Build rule for target.
convert-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert-test
.PHONY : convert-test

# fast build rule for target.
convert-test/fast:
	$(MAKE) -f samples/CMakeFiles/convert-test.dir/build.make samples/CMakeFiles/convert-test.dir/build
.PHONY : convert-test/fast

#=============================================================================
# Target rules for targets named easyaccess-test

# Build rule for target.
easyaccess-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 easyaccess-test
.PHONY : easyaccess-test

# fast build rule for target.
easyaccess-test/fast:
	$(MAKE) -f samples/CMakeFiles/easyaccess-test.dir/build.make samples/CMakeFiles/easyaccess-test.dir/build
.PHONY : easyaccess-test/fast

#=============================================================================
# Target rules for targets named xmpsample

# Build rule for target.
xmpsample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmpsample
.PHONY : xmpsample

# fast build rule for target.
xmpsample/fast:
	$(MAKE) -f samples/CMakeFiles/xmpsample.dir/build.make samples/CMakeFiles/xmpsample.dir/build
.PHONY : xmpsample/fast

#=============================================================================
# Target rules for targets named write2-test

# Build rule for target.
write2-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write2-test
.PHONY : write2-test

# fast build rule for target.
write2-test/fast:
	$(MAKE) -f samples/CMakeFiles/write2-test.dir/build.make samples/CMakeFiles/write2-test.dir/build
.PHONY : write2-test/fast

#=============================================================================
# Target rules for targets named prevtest

# Build rule for target.
prevtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prevtest
.PHONY : prevtest

# fast build rule for target.
prevtest/fast:
	$(MAKE) -f samples/CMakeFiles/prevtest.dir/build.make samples/CMakeFiles/prevtest.dir/build
.PHONY : prevtest/fast

#=============================================================================
# Target rules for targets named exifdata

# Build rule for target.
exifdata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exifdata
.PHONY : exifdata

# fast build rule for target.
exifdata/fast:
	$(MAKE) -f samples/CMakeFiles/exifdata.dir/build.make samples/CMakeFiles/exifdata.dir/build
.PHONY : exifdata/fast

#=============================================================================
# Target rules for targets named exifvalue

# Build rule for target.
exifvalue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exifvalue
.PHONY : exifvalue

# fast build rule for target.
exifvalue/fast:
	$(MAKE) -f samples/CMakeFiles/exifvalue.dir/build.make samples/CMakeFiles/exifvalue.dir/build
.PHONY : exifvalue/fast

#=============================================================================
# Target rules for targets named exifcomment

# Build rule for target.
exifcomment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exifcomment
.PHONY : exifcomment

# fast build rule for target.
exifcomment/fast:
	$(MAKE) -f samples/CMakeFiles/exifcomment.dir/build.make samples/CMakeFiles/exifcomment.dir/build
.PHONY : exifcomment/fast

#=============================================================================
# Target rules for targets named exifdata-test

# Build rule for target.
exifdata-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exifdata-test
.PHONY : exifdata-test

# fast build rule for target.
exifdata-test/fast:
	$(MAKE) -f samples/CMakeFiles/exifdata-test.dir/build.make samples/CMakeFiles/exifdata-test.dir/build
.PHONY : exifdata-test/fast

#=============================================================================
# Target rules for targets named mrwthumb

# Build rule for target.
mrwthumb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mrwthumb
.PHONY : mrwthumb

# fast build rule for target.
mrwthumb/fast:
	$(MAKE) -f samples/CMakeFiles/mrwthumb.dir/build.make samples/CMakeFiles/mrwthumb.dir/build
.PHONY : mrwthumb/fast

#=============================================================================
# Target rules for targets named iotest

# Build rule for target.
iotest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iotest
.PHONY : iotest

# fast build rule for target.
iotest/fast:
	$(MAKE) -f samples/CMakeFiles/iotest.dir/build.make samples/CMakeFiles/iotest.dir/build
.PHONY : iotest/fast

#=============================================================================
# Target rules for targets named addmoddel

# Build rule for target.
addmoddel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 addmoddel
.PHONY : addmoddel

# fast build rule for target.
addmoddel/fast:
	$(MAKE) -f samples/CMakeFiles/addmoddel.dir/build.make samples/CMakeFiles/addmoddel.dir/build
.PHONY : addmoddel/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalUpdate"
	@echo "... install"
	@echo "... ExperimentalStart"
	@echo "... NightlyMemCheck"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... ContinuousMemCheck"
	@echo "... uninstall"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalMemCheck"
	@echo "... edit_cache"
	@echo "... ContinuousConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... NightlyStart"
	@echo "... Nightly"
	@echo "... NightlyUpdate"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... exiv2-xmp"
	@echo "... exiv2"
	@echo "... exiv2lib"
	@echo "... exiv2lib_int"
	@echo "... remotetest"
	@echo "... geotag"
	@echo "... exiv2json"
	@echo "... pathtest"
	@echo "... metacopy"
	@echo "... getopt-test"
	@echo "... xmpdump"
	@echo "... xmpprint"
	@echo "... xmpparse"
	@echo "... stringto-test"
	@echo "... write-test"
	@echo "... iptctest"
	@echo "... tiff-test"
	@echo "... conntest"
	@echo "... largeiptc-test"
	@echo "... ini-test"
	@echo "... taglist"
	@echo "... xmpparser-test"
	@echo "... mmap-test"
	@echo "... key-test"
	@echo "... werror-test"
	@echo "... iptceasy"
	@echo "... iptcprint"
	@echo "... exifprint"
	@echo "... convert-test"
	@echo "... easyaccess-test"
	@echo "... xmpsample"
	@echo "... write2-test"
	@echo "... prevtest"
	@echo "... exifdata"
	@echo "... exifvalue"
	@echo "... exifcomment"
	@echo "... exifdata-test"
	@echo "... mrwthumb"
	@echo "... iotest"
	@echo "... addmoddel"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

